### ISSUE TITLE
macOS CMD build error (installation issue)

### ISSUE THREAD

**Issue by haircell** [kharchenkolab/pagoda2#108]
Hi, I'm a macOS Catalina v10.15.6 user and trying (unsuccessfully) to install Pagoda2. I followed the Wiki page here (https://github.com/kharchenkolab/pagoda2/wiki/Installing-Pagoda2-for-Mac-OS) by doing the following:
1. `brew install gcc gfortran llvm`
2. `nano ~/.zshrc `and add the following:

> export PATH="/usr/local/opt/llvm/bin:$PATH"
> export LDFLAGS="-L/usr/local/opt/llvm/lib"
> export CPPFLAGS="-I/usr/local/opt/llvm/include"
> 3. nano ~/.R/Makevars and add the following:
> XCBASE:=$(shell xcrun --show-sdk-path)
> LLVMBASE:=$(shell brew --prefix llvm)
> GCCBASE:=$(shell brew --prefix gcc)
> GETTEXT:=$(shell brew --prefix gettext)

> CC=$(LLVMBASE)/bin/clang -fopenmp
> CXX=$(LLVMBASE)/bin/clang++ -fopenmp
> CXX11=$(LLVMBASE)/bin/clang++ -fopenmp
> CXX14=$(LLVMBASE)/bin/clang++ -fopenmp
> CXX17=$(LLVMBASE)/bin/clang++ -fopenmp
> CXX1X=$(LLVMBASE)/bin/clang++ -fopenmp
> 
> CPPFLAGS=-isystem "$(LLVMBASE)/include" -isysroot "$(XCBASE)"
> LDFLAGS=-L"$(LLVMBASE)/lib" -L"$(GETTEXT)/lib" --sysroot="$(XCBASE)"
> 
> FC=$(GCCBASE)/bin/gfortran -fopenmp
> F77=$(GCCBASE)/bin/gfortran -fopenmp
> FLIBS=-L$(GCCBASE)/lib/gcc/9/ -lm

4. `git clone https://github.com/kharchenkolab/pagoda2.git`
5. `cd pagoda2`
6. `R CMD build .`

I initially had the following error:

> * checking for file ‘./DESCRIPTION’ ... OK
> * preparing ‘pagoda2’:
> * checking DESCRIPTION meta-information ... OK
> * cleaning src
> * installing the package to build vignettes
> * creating vignettes ... ERROR
> --- re-building ‘pagoda2.Rmd’ using rmarkdown
> Warning in engine$weave(file, quiet = quiet, encoding = enc) :
>   Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
> --- finished re-building ‘pagoda2.Rmd’
> 
> --- re-building ‘pagoda2.tutorial.goaspects.Rmd’ using rmarkdown
> Warning in engine$weave(file, quiet = quiet, encoding = enc) :
>   Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
> Quitting from lines 21-25 (pagoda2.tutorial.goaspects.Rmd) 
> Error: processing vignette 'pagoda2.tutorial.goaspects.Rmd' failed with diagnostics:
> there is no package called 'nbHelpers'
> --- failed re-building ‘pagoda2.tutorial.goaspects.Rmd’
> 
> --- re-building ‘pagoda2.walkthrough.Rmd’ using rmarkdown
> Warning in engine$weave(file, quiet = quiet, encoding = enc) :
>   Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Quitting from lines 241-253 (pagoda2.walkthrough.Rmd) 
> Error: processing vignette 'pagoda2.walkthrough.Rmd' failed with diagnostics:
> there is no package called 'colorRamps'
> --- failed re-building ‘pagoda2.walkthrough.Rmd’
> 
> SUMMARY: processing the following files failed:
>   ‘pagoda2.tutorial.goaspects.Rmd’ ‘pagoda2.walkthrough.Rmd’
> 
> Error: Vignette re-building failed.
> Execution halted

After installing `colorRamps` and `nbHelpers` in R, I tried again with `R CMD build .` and now get the following error:
```
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘pagoda2’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘pagoda2.Rmd’ using rmarkdown
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
--- finished re-building ‘pagoda2.Rmd’

--- re-building ‘pagoda2.tutorial.goaspects.Rmd’ using rmarkdown
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
Quitting from lines 29-31 (pagoda2.tutorial.goaspects.Rmd) 
Error: processing vignette 'pagoda2.tutorial.goaspects.Rmd' failed with diagnostics:
Matrix file does not exist
--- failed re-building ‘pagoda2.tutorial.goaspects.Rmd’

--- re-building ‘pagoda2.walkthrough.Rmd’ using rmarkdown
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
--- finished re-building ‘pagoda2.walkthrough.Rmd’

SUMMARY: processing the following file failed:
  ‘pagoda2.tutorial.goaspects.Rmd’

Error: Vignette re-building failed.
Execution halted
Error in appList[[i]] : subscript out of bounds
Calls: <Anonymous> -> <Anonymous> -> remove -> inherits
```

And if I try installing pagoda2 using R (`devtools::install_github('kharchenkolab/pagoda2')`), I get the usual macOS error:
```
clang: error: unsupported option '-fopenmp'
make[1]: *** [base.o] Error 1
make: *** [sublibraries] Error 1
ERROR: compilation failed for package ‘pagoda2’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/pagoda2’
Error: Failed to install 'pagoda2' from GitHub:
  (converted from warning) installation of package ‘/var/folders/g0/v1bzrcmn6kx6zpnx83d6_yv80000gp/T//Rtmpq9wuxq/file134051d09554e/pagoda2_0.1.2.tar.gz’ had non-zero exit status
```

Any guidance would be very much appreciated. Thank you!

**Comment by evanbiederstedt** [comment]
Hi @haircell 

I was just fixing this now actually :)  Give me a few minutes, and it should be working soon. I'll update you. 

The first problems you encountered were due to a vignette file; the other is due to OpenMP.

**Comment by evanbiederstedt** [comment]
So, the develop branch should (natively) install on Mac OS: 

https://builder.r-hub.io/status/pagoda2_0.1.3.tar.gz-86f7a3a0c7914faea228c785625a846e

There are warnings associated with CRAN suitability, but the package installs. 

I would like you to check this before pushing to master :) Here is what you can do:

(1)

Either go into your current subdirectory and try:

```
cd pagoda2
git pull origin devel --force ## if this doesn't work, try git fetch first
R CMD build .
R CMD INSTALL *gz
```

or if you have to clone from scratch

```
git clone https://github.com/kharchenkolab/pagoda2.git
cd pagoda2 
git pull origin devel --force ## if this doesn't work, try git fetch first
R CMD build .
R CMD INSTALL *gz
```

(2) Try the following https://cran.r-project.org/web/packages/githubinstall/vignettes/githubinstall.html

```
gh_install_packages("kharchenkolab/pagoda2", ref = "devel")
```

Please let me know how that goes :) If it works, I'll re-version and push to master

Best, Evan

**Comment by haircell** [comment]
Thanks for the quick response, Evan! 

So I tried option (1) above and cloning from scratch, but ran into these issues: 
```
git clone https://github.com/kharchenkolab/pagoda2.git
Cloning into 'pagoda2'...
remote: Enumerating objects: 174, done.
remote: Counting objects: 100% (174/174), done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 6579 (delta 70), reused 88 (delta 34), pack-reused 6405
Receiving objects: 100% (6579/6579), 32.86 MiB | 11.04 MiB/s, done.
Resolving deltas: 100% (4855/4855), done.
```
```
user/ pagoda2 % git pull origin devel --force
From https://github.com/kharchenkolab/pagoda2
 * branch            devel      -> FETCH_HEAD
CONFLICT (add/add): Merge conflict in .travis.yml
Auto-merging .travis.yml
Automatic merge failed; fix conflicts and then commit the result.
```
Then when I tried `git fetch pull origin devel --force`, I got the following error:
```
fatal: 'pull' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I also tried `gh_install_packages("kharchenkolab/pagoda2", ref = "devel")`. This goes through and I'm asked the following:
```
Select a number or, hit 0 to cancel. 

 1: QuackenbushLab/pandaR  
 2: bgreenwell/pkgbday     Determine the birthday and age of any R package on CRAN (warning: experimental and probably useless!)
 3: hansenlab/mpra         
 4: hansenlab/yamss        
 5: jmarlab/pathVar        This package contains the functions to find the pathways that have significantly different variability than a reference gene set. It also finds the categories from this pathway that are significant where each category is a cluster of genes. The genes are separated into clusters by their level of variability.
 6: klarakaleb/roma        R wrapper for the OMA REST API
 7: marchinilab/dropsim    R Package for Single Cell RNAseq Synthetic Data Simulation
 8: matthewwolak/nadiv     R package that constructs (non)additive genetic relationship matrices, and their inverses, from a pedigree to be used in linear mixed effect models (A.K.A. the 'animal model').
 9: mingchen-lab/cytosee   
10: pearselab/nacdb        Not A Community DataBase
```
Which one of these should I select? 

Thanks again!

**Comment by evanbiederstedt** [comment]
Hi @haircell 

It's strange `githubinstall` gives that error. 

In any sense, the easiest thing to do is `rm -rf pagoda2` and start from scratch with this:

```
git clone https://github.com/kharchenkolab/pagoda2.git
cd pagoda2 
git pull origin devel --force ## if this doesn't work, try git fetch first
R CMD build .
R CMD INSTALL *gz
```

Try that out and tell me if it works

Thanks, Evan

**Comment by haircell** [comment]
Looks like same issue:
```user ~ % rm -rf pagoda2
user ~ % git clone https://github.com/kharchenkolab/pagoda2.git
Cloning into 'pagoda2'...
remote: Enumerating objects: 174, done.
remote: Counting objects: 100% (174/174), done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 6579 (delta 70), reused 88 (delta 34), pack-reused 6405
Receiving objects: 100% (6579/6579), 32.86 MiB | 11.05 MiB/s, done.
Resolving deltas: 100% (4855/4855), done.
user ~ % cd pagoda2 
user pagoda2 % git pull origin devel --force
From https://github.com/kharchenkolab/pagoda2
 * branch            devel      -> FETCH_HEAD
CONFLICT (add/add): Merge conflict in .travis.yml
Auto-merging .travis.yml
Automatic merge failed; fix conflicts and then commit the result.
user pagoda2 % git fetch pull origin devel --force
fatal: 'pull' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
user pagoda2 % 
```
Thanks again, @evanbiederstedt

**Comment by evanbiederstedt** [comment]
Sorry, typing too fast---try this, there's a step missing, `git checkout devel `:

```
git clone https://github.com/kharchenkolab/pagoda2.git
cd pagoda2 
git checkout devel 
git pull origin devel --force ## if this doesn't work, try git fetch first
R CMD build .
R CMD INSTALL *gz
```

**Comment by haircell** [comment]
@evanbiederstedt 
I started over by removing pagoda2 directory and doing the following. Getting this now :) 

```
user ~ % git clone https://github.com/kharchenkolab/pagoda2.git
Cloning into 'pagoda2'...
remote: Enumerating objects: 174, done.
remote: Counting objects: 100% (174/174), done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 6579 (delta 70), reused 88 (delta 34), pack-reused 6405
Receiving objects: 100% (6579/6579), 32.86 MiB | 11.03 MiB/s, done.
Resolving deltas: 100% (4855/4855), done.
user ~ % cd pagoda2
user pagoda2 % git checkout devel
Branch 'devel' set up to track remote branch 'devel' from 'origin'.
Switched to a new branch 'devel'
user pagoda2 % git pull origin devel --force
From https://github.com/kharchenkolab/pagoda2
 * branch            devel      -> FETCH_HEAD
Already up to date.
user pagoda2 % R CMD build .
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘pagoda2’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘pagoda2.Rmd’ using rmarkdown
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
--- finished re-building ‘pagoda2.Rmd’

--- re-building ‘pagoda2.tutorial.goaspects.Rmd’ using rmarkdown
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
Quitting from lines 29-31 (pagoda2.tutorial.goaspects.Rmd) 
Error: processing vignette 'pagoda2.tutorial.goaspects.Rmd' failed with diagnostics:
Matrix file does not exist
--- failed re-building ‘pagoda2.tutorial.goaspects.Rmd’

--- re-building ‘pagoda2.walkthrough.Rmd’ using rmarkdown
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
--- finished re-building ‘pagoda2.walkthrough.Rmd’

SUMMARY: processing the following file failed:
  ‘pagoda2.tutorial.goaspects.Rmd’

Error: Vignette re-building failed.
Execution halted
Error in appList[[i]] : subscript out of bounds
Calls: <Anonymous> -> <Anonymous> -> remove -> inherits
user pagoda2 % 
```

**Comment by evanbiederstedt** [comment]
Try `R CMD build . --no-vignettes` instead please

**Comment by haircell** [comment]
```
user pagoda2 % R CMD build . --no-vignettes
Error: '--no-vignettes' is defunct:
  use '--no-build-vignettes' instead
Execution halted
```

**Comment by evanbiederstedt** [comment]
Updated. This should work now:

```
git clone https://github.com/kharchenkolab/pagoda2.git
cd pagoda2 
git checkout devel 
git pull origin devel --force ## if this doesn't work, try git fetch first
R CMD build .
R CMD INSTALL *gz
```

**Comment by haircell** [comment]
Hurray, it worked!! :) 
Thanks, @evanbiederstedt !!! 

I just ran through an old analysis I had with my dataset using pagoda2 before upgrading my mac. It went through smoothly. I'm going to try to install `conos` now, which I had trouble with before...

**Comment by evanbiederstedt** [comment]
Glad it worked. 

The plan has been to add CRAN packages to conos, but that's still somewhat of a work in progress, given CRAN reviews take time. So that could still have some lingering issues. 

Please try the `dev` branch here: https://github.com/kharchenkolab/conos/tree/dev using similar instructions. 

Discussion here:
https://github.com/kharchenkolab/conos/issues/56
It looks like you previously had it working :)

There may be some lingering issue unfortunately, but it should be more robust soon.
