### ISSUE TITLE
adjustVariance "fatal error" in R

### ISSUE THREAD

**Issue by haircell** [kharchenkolab/pagoda2#110]
Hi All,

I successfully installed (re-installed) `pagoda2`, but now having the same issues that I encountered recently with 10x data: when I run `r$adjustVariance(plot=T,gam.k=10)`, my R crashes - I get the `R Session Aborted` screen with `R encountered a fatal error. The session was terminated.` message. I tried this with 3 different 10x datasets and get the same result. When I run smartseq2 dataset through, I do not encounter this issue. This seems to be a different problem than https://github.com/kharchenkolab/pagoda2/issues/38

Below is what I ran: 

```
my.data <- Read10X("~/sample1/raw_feature_bc_matrix")
cd <- my.data
str(cd)
par(mfrow=c(1,2), mar = c(3.5,3.5,2.0,0.5), mgp = c(2,0.65,0), cex = 1.0)
hist(log10(colSums(cd)+1),main='molecules per cell',col='wheat',xlab='log10[ molecules per cell]')
hist(log10(rowSums(cd)+1),main='molecules per gene',col='wheat',xlab='log10[ molecules per gene]')
counts <- gene.vs.molecule.cell.filter(cd,min.cell.size=500)
str(counts)
hist(log10(rowSums(counts)+1),main='Molecules per gene',xlab='molecules (log10)',col='wheat')
abline(v=1,lty=2,col=2)
counts <- counts[rowSums(counts)>=10,]
str(counts)
r <- Pagoda2$new(counts,log.scale=TRUE)
rownames(counts) <- make.unique(rownames(counts))
r <- Pagoda2$new(counts,log.scale=TRUE, n.cores=20)

r$adjustVariance(plot=T,gam.k=10)

```

Any guidance would be appreciated. Thank you!

**Comment by evanbiederstedt** [comment]
I would guess given your Mac OS didn't use OpenMP for the installation, you cannot use `n.cores=20`. `n.cores=1` should work. 

(On a side note, I'm guessing `n.cores=20` on your macbook doesn't quite make sense...)

I really know of no way around this, and getting binaries on CRAN won't help, as far as I know. 

You should try re-installing with https://github.com/kharchenkolab/pagoda2/wiki/Installing-Pagoda2-for-Mac-OS

I'll research how this is resolve elsewhere...but I don't think it really is. Mac OS users need to install from source, and figure out how to compile the code with the `-fopenmp` flags, as detailed in the wiki.

**Comment by evanbiederstedt** [comment]
The other option is that I will add these conditionals in the Cpp code such that if a user installs the R package without OpenMP and uses `n.cores>1`, it will throw an error.

**Comment by evanbiederstedt** [comment]
Actually @haircell , I *might* have found a solution. 

You still shouldn't be using `n.cores=20` on your macbook of course, but hopefully this doesn't result in segaults. 

Please try in the `devel` branch again, and let me know:

```
git clone https://github.com/kharchenkolab/pagoda2.git
cd pagoda2 
git checkout devel 
git pull origin devel --force ## if this doesn't work, try git fetch first
R CMD build .
R CMD INSTALL *gz
```

**Comment by evanbiederstedt** [comment]
@haircell  I just tried re-installing without openmp on my macbook, given changes in the `devel` branch

I think the `R encountered a fatal error. The session was terminated.` is now truly fixed. Please have another look. 

Let me know if that resolves your issues, and I can push to master/re-version.

Thanks, Evan

**Comment by haircell** [comment]
Thanks, @evanbiederstedt. 
I did change the number of cores to 1, and tried re-installing as you indicated above. Still get the fatal error unfortunately. I'm going to restart everything and try installation again.

**Comment by evanbiederstedt** [comment]
Yes, please try the `devel` branch:

```
git clone https://github.com/kharchenkolab/pagoda2.git
cd pagoda2 
git checkout devel 
git pull origin devel --force ## if this doesn't work, try git fetch first
R CMD build .
R CMD INSTALL *gz
```

**Comment by evanbiederstedt** [comment]
I updated the master branch. Please re-install from there. 

Either `devtools::github_install("kharchenkolab/pagoda2")` or 

```
git clone https://github.com/kharchenkolab/pagoda2.git
cd pagoda2 
R CMD build .
R CMD INSTALL *gz
```

**Comment by haircell** [comment]
Thanks @evanbiederstedt 
I removed `conos` and `pagoda2`, then re-installed using git clone per your above instructions. Installation is successful, but unfortunately still get the fatal error when trying to run `r$adjustVariance(plot=T,gam.k=10)`. I did set the number of cores to 1. I also removed `pagoda2` again and re-installed it using `devtools::install_github("kharchenkolab/pagoda2")` with the same result.

**Comment by haircell** [comment]
As a side note: Despite the successful installation, I do get quite a few warnings throughout the log. I've attached it as a `.txt` file here if this would help with the diagnosis. 
[pagoda2 installation log.txt](https://github.com/kharchenkolab/pagoda2/files/5321049/pagoda2.installation.log.txt)

**Comment by evanbiederstedt** [comment]
> As a side note: Despite the successful installation, I do get quite a few warnings throughout the log. I've attached it as a .txt file here if this would help with the diagnosis.

Based on the logs provided, everything was successful. Everything looks correct.

>I removed conos and pagoda2, then re-installed using git clone per your above instructions. Installation is successful, but unfortunately still get the fatal error when trying to run r$adjustVariance(plot=T,gam.k=10). I did set the number of cores to 1. I also removed pagoda2 again and re-installed it using devtools::install_github("kharchenkolab/pagoda2") with the same result.

Unfortunately, I'm just not able to currently replicate the error you're describing. 

Do you get the same error going through the walkthrough here?: https://github.com/kharchenkolab/pagoda2/blob/master/vignettes/pagoda2.walkthrough.Rmd

If not, I am guessing there's something wrong with the inputs here `my.data <- Read10X("~/sample1/raw_feature_bc_matrix")`, which I cannot easily debug from here.

**Comment by haircell** [comment]
Yes, I'm able to run the walkthrough you referenced. It must be the read10x then. I'm using seurat's `Read10X()` function. 

But I also tried this one: 
```
t.load.10x.data <- function(matrixPaths) {
  require(parallel)
  require(Matrix)
  mclapply(sn(names(matrixPaths)),function(nam) {
    matrixPath <- matrixPaths[nam];
    # read all count files (*_unique.counts) under a given path
    #cat("loading data from ",matrixPath, " ");
    x <- as(readMM(paste(matrixPath,'matrix.mtx',sep='/')),'dgCMatrix'); # convert to the required sparse matrix representation
    cat(".")
    gs <- read.delim(paste(matrixPath,'genes.tsv',sep='/'),header=F)
    rownames(x) <- gs[,2]
    cat(".")
    gs <- read.delim(paste(matrixPath,'barcodes.tsv',sep='/'),header=F)
    colnames(x) <- gs[,1]
    cat(".")
    colnames(x) <- paste(nam,colnames(x),sep='_');
    x
  },mc.cores=30)
}
```

When I run: `cd <- t.load.10x.data(list(VS="~/Desktop/R working directory/mydata/filtered_feature_bc_matrix"))`, I get the following error:
```Error in open.connection(file) : cannot open the connection
In addition: Warning message:
In open.connection(file) :
 
 Error in open.connection(file) : cannot open the connection 
9.
open.connection(file) 
8.
open(file) 
7.
readMM(paste(matrixPath, "matrix.mtx", sep = "/")) 
6.
.class1(object) 
5.
as(readMM(paste(matrixPath, "matrix.mtx", sep = "/")), "dgCMatrix") 
4.
FUN(X[[i]], ...) 
3.
lapply(X = X, FUN = FUN, ...) 
2.
mclapply(sn(names(matrixPaths)), function(nam) {
    matrixPath <- matrixPaths[nam]
    x <- as(readMM(paste(matrixPath, "matrix.mtx", sep = "/")), 
        "dgCMatrix") ... 
1.
t.load.10x.data(list(VS = "~/Desktop/R working directory/mydata/filtered_feature_bc_matrix")) 
```
I tried this with both the filtered_feature_bc_matrix files and the raw_feature_bc_matrix folder. The contents are the usual 10x files `barcodes.tsv.gz`, `features.tsv.gz`, and `matrix.mtx.gz`
Does it matter for pagoda if it's raw vs filtered data? 
Thanks again, @evanbiederstedt

**Comment by evanbiederstedt** [comment]
You might want to try this function: https://github.com/kharchenkolab/pagoda2/blob/master/R/helpers.R#L309

Otherwise, as described here
https://github.com/kharchenkolab/pagoda2/blob/master/inst/pagoda2.tutorial.goaspects.Rmd

there's a function `read10xMatrix()` in @barkasn's package https://github.com/barkasn/nbHelpers

>It must be the read10x then. I'm using seurat's Read10X() function.

In any case, the error you have been getting is associated with inputting data structures into the C++ functions which are unexpected. We should probably do a better job at checking for this. 

I'm glad we have that figured out; I'll close this issue
