### ISSUE TITLE
fac2col not found

### ISSUE THREAD

**Issue by cstubben** [kharchenkolab/pagoda2#113]
I'm following the tutorial and get an object 'fac2col' not found error.   I searched this Github site for fac2col and it's used but never defined as a function?

```
cell.colors <- pagoda2:::fac2col(cluster.label)
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'fac2col' not found
```

**Comment by pkharchenko** [comment]
I think it got moved to sccore. What branch are you using?

**Comment by cstubben** [comment]
I just installed from github today, so the most recent..  And this works no problem
`cell.colors <- sccore:::fac2col(cluster.label)`

**Comment by pkharchenko** [comment]
Oh, I see. This must be a tutorial vignette issue. 
Thanks!

**Comment by evanbiederstedt** [comment]
Hi @cstubben 

Thanks for the issue. 

Yes, `fac2col()` is now a function with sccore: https://github.com/kharchenkolab/sccore

It's not even an internal function with pagoda2 anymore, so this won't work:

```
cell.colors <- pagoda2:::fac2col(cluster.label)
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'fac2col' not found
```

> I'm following the tutorial and get an object 'fac2col' not found error.

Could you share which tutorial you're using? I couldn't find this function call used in any of the tutorial/vignettes for pagoda2. 

There is this tutorial with velocyto, which we should probably update:

http://pklab.med.harvard.edu/velocyto/notebooks/R/DG1.nb.html
```
emat <- ldat$spliced; nmat <- ldat$unspliced
emat <- emat[,rownames(r$counts)]; nmat <- nmat[,rownames(r$counts)]; # restrict to cells that passed p2 filter
# take cluster labels
cluster.label <- r$clusters$PCA[[1]]
cell.colors <- pagoda2:::fac2col(cluster.label)
# take embedding
emb <- r$embeddings$PCA$tSNE
```

Thanks, Evan

**Comment by cstubben** [comment]
Yes, I was following the velocyto tutorial in the link above. Thanks!

**Comment by evanbiederstedt** [comment]
Thanks @cstubben 

We'll correct, and I'll let you know when they're online. 

In the meantime of course, you can do `cell.colors <- pagoda2::fac2col(cluster.label)`

**Comment by evanbiederstedt** [comment]
We updated the link http://pklab.med.harvard.edu/velocyto/notebooks/R/DG1.nb.html

Thanks!
