### ISSUE TITLE
read.10x.matrices() - Error with Cell Ranger v3.x data

### ISSUE THREAD

**Issue by AmelZulji** [kharchenkolab/pagoda2#116]
Hi folks, 

read.10x.matrices() (pagoda2 v 0.1.4) produces following error when loading data aligned with Cell Ranger v3.x : 

```
reading 1 dataset(s) 
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file './outs/filtered_feature_bc_matrix//genes.tsv': No such file or directory
```

The problem is that in Cell Ranger v3.x genes are named as features. Following function works: 

```
sn <- function(x) { names(x) <- x; return(x); }

read.10x.matrices <- function (matrixPaths, n.cores = 1, verbose = TRUE) 
{
  if (length(matrixPaths) == 1) {
    matrixPaths <- c(one = matrixPaths)
    single.dataset <- TRUE
  }
  else {
    single.dataset <- FALSE
  }
  if (verbose) 
    message("reading ", length(matrixPaths), " dataset(s) ")
  if (is.null(names(matrixPaths))) 
    stop("matrixPaths must be a named vector")
  dl <- pagoda2:::papply(sn(names(matrixPaths)), function(nam) {
    matrixPath <- matrixPaths[nam]
    fn <- paste(matrixPath, "matrix.mtx", sep = "/")
    if (file.exists(fn)) {
      x <- as(readMM(fn), "dgCMatrix")
    }
    else if (file.exists(paste(fn, "gz", sep = "."))) {
      x <- as(readMM(gzcon(file(paste(fn, "gz", sep = "."), 
                                "rb"))), "dgCMatrix")
    }
    else {
      stop(paste("cant open", fn))
    }
    fn <- paste(matrixPath, "features.tsv", sep = "/")
    if (file.exists(paste(fn, "gz", sep = "."))) {
      fn <- paste(fn, "gz", sep = ".")
    }
    gs <- read.delim(fn, header = FALSE)
    rownames(x) <- gs[, 2]
    fn <- paste(matrixPath, "barcodes.tsv", sep = "/")
    if (file.exists(paste(fn, "gz", sep = "."))) {
      fn <- paste(fn, "gz", sep = ".")
    }
    gs <- read.delim(fn, header = FALSE)
    colnames(x) <- gs[, 1]
    if (verbose) 
      message(".")
    colnames(x) <- paste(nam, colnames(x), sep = "_")
    x
  }, n.cores = n.cores)
  if (verbose) 
    message(" done")
  if (single.dataset) {
    return(dl[[1]])
  }
  else {
    return(dl)
  }
}
```

Best regards,
Amel Zulji

**Comment by evanbiederstedt** [comment]
Hi @AmelZulji 

Thanks for using pagoda2. 

Although I haven't made a release yet, the current version of pagoda2 you can install via `devtools::install_github('kharchenkolab/pagoda2')` is version `1.0.0`. 

I noticed the issue you described a few weeks ago and fixed it, I think. Please give it a try. 

https://github.com/kharchenkolab/pagoda2/blob/master/R/helpers.R#L309-L362

There's also the function `read10xMatrix()` here: https://github.com/kharchenkolab/pagoda2/blob/master/R/helpers.R#L454

Please give this a try as well. I think it should be faster. 

Let me know if that works. Thanks, Evan

**Comment by evanbiederstedt** [comment]
Hi @AmelZulji  

I think this resolves the issue. Let me know if that doesn't work. Thanks, Evan

**Comment by AmelZulji** [comment]
Hi @evanbiederstedt,

Sorry for the delayed response. 

Unfortunately, `read10xMatrix()` from pagoda2 v1.0.0 doesn't work for me. I tried specifying both `version = "V3"` and `version = "V2"`, but they produce the same error: 

```
Reading in matrix...
Error in open.connection(file) : cannot open the connection
In addition: Warning messages:
1: In file(file) :
  'raw = FALSE' but './outs/filtered_feature_bc_matrix//' is not a regular file
2: In open.connection(file) :
  cannot open file './outs/filtered_feature_bc_matrix//': it is a directory
```

The function I mentioned in the first post is still working fine with pagoda2 v1.0.0.

Do you have an idea what could be the problem?

Thank you and kind regards,
Amel Zulji

**Comment by evanbiederstedt** [comment]
Hi @AmelZulji 

Thanks for following up with this.

Do you have the a link to the data format you're using with 10x? If you show me this URL, I can download it and debug along with you. Please save your full command as well.

**Comment by AmelZulji** [comment]
Hi @evanbiederstedt, 

We generated these data in our lab, and are not yet publicly available. Can I provide any other information which can of help for debugging?

**Comment by AmelZulji** [comment]
Sorry, I completely misunderstood that 😄. 

So, we have single cell gene expression (V2 chemistry) dataset. It was aligned with Cell Ranger v 3.0.2 against the reference transcriptome modified to include intronic regions.

**Comment by evanbiederstedt** [comment]
Hi @AmelZulji 

Thanks. Could you find the corresponding example dataset from the 10x website? It would be useful to double check on my part how to best fix this issue. 

I appreciate the help. Thank you, Evan

**Comment by AmelZulji** [comment]
Hi @evanbiederstedt,

The closest to our dataset is this: 
https://support.10xgenomics.com/single-cell-gene-expression/datasets/2.1.0/nuclei_2k 

Hopefully you can reproduce the error. Let me know if further info are needed.

Thanks for helping out. 

Best,
Amel

**Comment by evanbiederstedt** [comment]
Hi @AmelZulji 

Sorry, I somehow missed your response. 

You're entirely right that I have a bug here. I've updated (and hopefully fixed) the code in the `devel` branch here: https://github.com/kharchenkolab/pagoda2/tree/devel

Not that the link you shared above is CellRange v2.x data. So, the following does work for me

```
mydata = read10xMatrix("/Users/evanbiederstedt/Downloads/filtered_gene_bc_matrices2/mm10", version="V2")
```

In order to install from the package from the `devel` branch, try 

```
git clone https://github.com/kharchenkolab/pagoda2.git
cd pagoda2
git checkout devel
git pull origin devel --force
R CMD BUILD . --no-build-vignettes
R CMD INSTALL *gz 
```

The new code is here: https://github.com/kharchenkolab/pagoda2/blob/devel/R/helpers.R#L445-L517

Let me know if it works for you. Apologies again for the delays. 

Thanks, Evan

**Comment by evanbiederstedt** [comment]
Hi @AmelZulji 

The other thing is that the package has recently been published on CRAN, but this function will still have these bugs in version 1.0.0

So I'll re-version soon. 

Again, please let me know if this works.

Best, Evan

**Comment by evanbiederstedt** [comment]
This should be on version 1.0.1, which we'll hopefully push to the main branch soon. 

Here is the code which should work:

```
#' This function reads a matrix generated by the 10x processing pipeline
#' from the specified directory and returns it. It aborts if one of the required
#' files in the specified directory do not exist.
#'
#' @param path string Location of 10x output
#' @param version string Version of 10x output to read (default='V3'). Must be one of 'V2' or 'V3'.
#' @param transcript.id string Transcript identifier to use (default='SYMBOL'). Must be either 'SYMBOL' (e.g. "Sox17") or 'ENSEMBL' (e.g. "ENSMUSG00000025902"). This value is case-sensitive.
#' @param verbose boolean Whether to return verbose output
#' @return parsed 10x outputs into a matrix
#'
#' @export 
read10xMatrix <- function(path, version='V3', transcript.id = 'SYMBOL', verbose=TRUE) {

  if (!requireNamespace("data.table", quietly=TRUE)){
    stop("You need to install package 'data.table' to be able to use this function.")
  }

  ## check if path exists
  if (!dir.exists(path)){
    stop("Path provided does not exist. The path should be the folder of filtered gene/cell matrix provided by 10x.")
  }

  if (version != 'V2' && version != 'V3'){
    stop('Unknown value for "version", it must be either "V2" or "V3"')
  }
  if (transcript.id != 'SYMBOL' && transcript.id != 'ENSEMBL') {
    stop('Unknown transcript identifier "transcript.id", it must be either "SYMBOL" or "ENSEMBL". This input is case-sensitive.')
  }
  matrixFile <- paste0(path, '/', list.files(path=path)[grepl("matrix", list.files(path=path))])
  barcodesFile <- paste0(path, '/', list.files(path=path)[grepl("barcodes", list.files(path=path))])
  if (version == 'V2') {
    genesFile <- paste0(path, '/', list.files(path=path)[grepl("genes", list.files(path=path))])
    ## double-check version arg provided isn't wrong
    if (!grepl("genes", genesFile)){
      stop("Cannot find a 'genes' file. You specified version='V2'---please check if this is correct. Is this actually v3.x? Otherwise, the file cannot be found in the path provided. Please check.")
    }
  } else if (version == 'V3') {
    genesFile <- paste0(path, '/', list.files(path=path)[grepl("features", list.files(path=path))])
    ## double-check version arg provided isn't wrong
    if (!grepl("features", genesFile)){
      stop("Cannot find a 'features' file. You specified version='V3'---please check if this is correct.  Is this actually v2.x? Otherwise, the file cannot be found in the path provided. Please check.")
    }
  }
  if (!file.exists(matrixFile)) { 
    stop('Matrix file does not exist, or cannot be found in the path provided. Please check.')  
  }
  if (!file.exists(barcodesFile)) { 
    stop('Barcodes file does not exist, or cannot be found in the path provided. Please check.') 
  }

  if (verbose) message("Reading in matrix...")
  x <- as(Matrix::readMM(matrixFile), 'dgCMatrix')
  if (verbose) {
    if (version == 'V2') {
      message("Reading in genes...")
    } else if (version == 'V3') {
      message("Reading in features...")
    }
  }
  ## still faster to use fread() I think...
  genes <- data.table::fread(genesFile, header=FALSE, col.names = c("SYMBOL", "ENSEMBL"))
  ## rownames is a poor design, but the output format was already set
  if (transcript.id == 'SYMBOL'){
    rownames(x) <- genes[[2]]
  } else if (transcript.id == 'ENSEMBL') {
    rownames(x) <- genes[[1]]
  }
  if (verbose) message("Reading in barcodes...")
  barcodes <- data.table::fread(barcodesFile, header=FALSE)
  colnames(x) <- barcodes[[1]]
  invisible(x)
}
```

Thanks, Evan

**Comment by AmelZulji** [comment]
Hi @evanbiederstedt,

In my particular case, I had 10x genomics V2 platform, and data were aligned with Cell Ranger 3.0.1. I could not find this particular combination on 10x website and the mouse data I have sent was the closest to what I have.

For me `read10xMatrix()` doesnt work. Will check whether provided function works.

Thank you for helping out!

Best,
Amel

**Comment by evanbiederstedt** [comment]
Hi @AmelZulji 

Yes, please try it out with the new function. 

It may be useful to try to install the package from `devel`:

```
git clone https://github.com/kharchenkolab/pagoda2.git
cd pagoda2
git checkout devel
git pull origin devel --force
R CMD BUILD . --no-build-vignettes
R CMD INSTALL *gz 
```
