### ISSUE TITLE
mc.cores >1 not supported on Windows

### ISSUE THREAD

**Issue by markdunning** [kharchenkolab/pagoda2#120]
Hello,

I am trying to use pagoda2 to create a web app for some 10X data. I get to the extendedP2proc step, but the error message appears

```
determining valid pathways
Error in mclapply(sn(gsl), function(go) sum(unique(get(go, envir = setenv)) %in%  : 
  'mc.cores' > 1 is not supported on Windows
```

Is there way to make this work on Windows? There doesn't seem to be a way to turn off the use of multiple cores if the user has a Windows machine.

Regards,
Mark

**Comment by markdunning** [comment]
Update: so I have managed to run the example in the Walkthrough successfully. So I guess the problem must be with my input data. e.g. gene names not being in the expected format.

**Comment by evanbiederstedt** [comment]
Hi @markdunning 

Thanks for using pagoda2. 

Yes, the issue is with the function `testPathwayOverdispersion`. Try walking through the second part of the tutorial, "II. In-Depth Processing and Analysis" whereby each function is used individually. The issue might be more easy to debug.
