### ISSUE TITLE
Unable to view genes associated with GO terms

### ISSUE THREAD

**Issue by n1tian** [kharchenkolab/pagoda2#121]
Hi,

I'm trying to use the Pagoda2 interactive app to view genes associated with different GO terms and keep getting the error "Error in x[["name"]] : subscript out of bounds" when I click on GO terms. However, the pagoda app (p2app) has genes under these GO terms (geneSets). Is there a reason for this? I even tried the same code on the PBMC example data and didn't see this problem. 

Thank you!

**Comment by evanbiederstedt** [comment]
Hi @n1tian 

You might need to give me more code + the data you're using to debug this properly. 

If this issue doesn't occur with the walkthrough tutorial, try to isolate the step in question and work from there. 

Thanks, Evan

**Comment by n1tian** [comment]
Hi @evanbiederstedt,

Thank you for your response! It's because I was using the genome annotation for human to our mouse data. After changing to the mouse library, it worked!
