### ISSUE TITLE
Error in extendedP2proc

### ISSUE THREAD

**Issue by markdunning** [kharchenkolab/pagoda2#122]
Hello,

I'm trying to build a serialised web app but am having problems with the extendedP2proc step. It seems that the function starts to work, but I get an error in the reducing redundancy step or testing pathway overdispersion

```
> pext.res <- extendedP2proc(p2.processed, organism = "mm")

determining valid pathways
processing 2629 valid pathways
scoring pathway od signifcance
compiling pathway reduction
clustering aspects based on gene loading ... 61 aspects remaining
clustering aspects based on pattern similarity ...  aspects remaining

Error in 1:nrow(tam3$xv) : argument of length 0
```

Do you have any suggestions on how I can fix or debug this? Many thanks

I am running pagoda2 via docker

**Comment by evanbiederstedt** [comment]
Hi @markdunning 

The function is essentially a wrapper around `testPathwayOverdispersion()`

https://github.com/kharchenkolab/pagoda2/blob/master/R/pipelineHelpers.R#L70-L103

That function `testPathwayOverdispersion()` is here: https://github.com/kharchenkolab/pagoda2/blob/master/R/Pagoda2.R#L2210-L2231 and is essentially legacy code from SCDE. 

For debugging, I would check these lines: https://github.com/kharchenkolab/pagoda2/blob/master/R/Pagoda2.R#L2436-L2449

It looks like `tam3` is empty---it's a bit difficult to debug without the data on hand. 

If you find the issue, let us know---I'm happy to write in a few catches to resolve this behavior. 

Thanks, Evan

**Comment by evanbiederstedt** [comment]
Hi @markdunning 

You had another question as well. If you send me some data, I could try to help debug. Use my email. 

Best, Evan
