### ISSUE TITLE
Exporting lists of genesets within aspects

### ISSUE THREAD

**Issue by BW093** [kharchenkolab/pagoda2#128]
Hi,

I was wondering if you could help me out with extracting some data from the pagoda2 UI. I am trying to export the data within each aspect as a table. Is there is a way to download the gene sets, scores and count information that make up these aspects (e.g. in screenshot below i want all the data from the 'genesets in aspect' dataset. 
![image](https://user-images.githubusercontent.com/93206749/138901126-ad7c9b1f-f46d-463a-b550-89907a45cc20.png).

If this is not yet possible in the UI, but is within R, any help with doing that would also be much appreciated too.

Thank you very much.

**Comment by evanbiederstedt** [comment]
Hi @BW093 

I've added this feature into the pagoda2 frontend app. Basically, users should click on the floppy disk icon/button to export the data shown in the grid as a *csv file. It is a somewhat basic implementation, but I hope it works for your purposes. 

This button doesn't retrieve all of the data stored (i.e. there is no sever-side rendering here, it's only client-side); only the data rendered in the grid is downloaded in the *csv. 

Here is a screenshot indicating where you should be able to click:
<img width="419" alt="Screen Shot 2021-11-14 at 7 54 31 PM" src="https://user-images.githubusercontent.com/6968193/141706660-f504cfd8-945f-4ebf-bf7b-5a8900b8ac80.png">

This works now for the grids "Gene sets in Aspect", "Genes in the selected Gene Set", and "Genes in Selected Gene Set".

Best, Evan

**Comment by yfwang27** [comment]
Hi @evanbiederstedt ,

Thank you very much for providing a solution to our request. However, when I tried to re-install the new version in R with 
devtools::install_github('kharchenkolab/pagoda2') 

It returns error message as below and it'd be great if you could look into this.

Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'pagoda2' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 57/60
  Rate limit reset at: 2021-12-04 13:54:40 UTC

Thank you very much.

**Comment by evanbiederstedt** [comment]
Hi @yfwang27 

This is a error related to devtools: https://github.com/r-lib/remotes/issues/330

It's not related to pagoda2; please see the discussion in the link above. 

In terms of installation, try with CRAN i.e. `install.pakcages()`
