### ISSUE TITLE
Trying to run Pagoda2 on Seurat pre-processed data

### ISSUE THREAD

**Issue by airfan0** [kharchenkolab/pagoda2#129]
Hi,

I am trying to use your algorithm for some pathway analysis on my scRNA seq data. I have already pre-processed the data using the Seurat pipeline, so I was wondering if there was any way we can just use the normalized data from Seurat as input for your algorithm? I tried using the following command where 'rawData' is my Seurat object, but I get the following error message.
<img width="723" alt="image" src="https://user-images.githubusercontent.com/98128631/156237999-abfa6aad-34b5-4d5d-8a45-33d33e29f568.png">
<img width="917" alt="image" src="https://user-images.githubusercontent.com/98128631/156238062-c034df98-d021-4285-9b58-a5f241bbe7f0.png">

**Comment by evanbiederstedt** [comment]
Hi @airfan0 

I think this answer would be useful: https://github.com/kharchenkolab/pagoda2/issues/49

It's possible this will work: 
```
p2 <- Pagoda2$new(as(so@scale.data, "dgCMatrix"), modelType="raw")
```

That said, you may need to dig into what precisely is going wrong above. `subscript out of bounds` is a standard R error, e.g.
```
> matrix(1, 2)
> matrix(1, 2)[, 3]
## Error in matrix(1, 2)[, 3] : subscript out of bounds
```

The error isn't with pagoda2, but rather `t(rawData[["RNA"]]@scale.data)[rownames(pgd$counts), colnames(pgd$counts)]`

It will be tricky to debug this without seeing your data. After looking at the issue above, you should dig around here to figure out what the R code is doing: https://github.com/kharchenkolab/pagoda2/blob/main/R/Pagoda2.R

Hope this helps

Best, Evan

**Comment by airfan0** [comment]
Hi Evan!

Thanks for the help! Yes, that seemed to help! I am now trying to run the overdispersion analysis by starting with making the GO environment. However, I am encountering the following error: 
<img width="919" alt="image" src="https://user-images.githubusercontent.com/98128631/156445898-d78028d5-29c8-4cba-bab3-3f191c212121.png">
As a reference, my matrix is in the following format. Do I need to change the gene name to another type of identifier?
<img width="907" alt="image" src="https://user-images.githubusercontent.com/98128631/156446023-9f27054c-29f8-4e49-a6cc-167444474874.png">

**Comment by evanbiederstedt** [comment]
Hi @airfan0 

I think you're getting this from the tutorial: https://github.com/kharchenkolab/pagoda2/blob/main/doc/pagoda2.walkthrough.md

```
# translate gene names to ids
ids <- unlist(lapply(mget(colnames(r$counts), org.Hs.egALIAS2EG, ifnotfound=NA), function(x) x[1]))
# reverse map
rids <- names(ids)
names(rids) <- ids
# list all the ids per GO category
go.env <- list2env(eapply(org.Hs.egGO2ALLEGS,function(x) as.character(na.omit(rids[x]))))
```

You're probably having difficulty with this:  `org.Hs.egALIAS2EG`

https://bioconductor.org/packages/release/data/annotation/html/org.Hs.eg.db.html

There are lots of gene names to doublecheck there; the strings are primarily based on Entrez Gene. 

So step back: just translate the gene names in your dataset to unique IDs. That is really all this code does. 

Hopefully that helps.
