### ISSUE TITLE
installing problem

### ISSUE THREAD

**Issue by ch8316f5eyu** [kharchenkolab/pagoda2#130]
When I install pagoba2 by "install.packages('pagoda2')", I can't install its dependency "N2R".
There is the error message:
`x86_64-conda-linux-gnu-c++ -std=gnu++11 -I"/home/weiyu/miniconda3/envs/r4/lib/R/include" -DNDEBUG  -I'/home/weiyu/miniconda3/envs/r4/lib/R/library/Rcpp/include' -I'/home/weiyu/miniconda3/envs/r4/lib/R/library/RcppSpdlog/include' -I'/home/weiyu/miniconda3/envs/r4/lib/R/lib
rary/RcppEigen/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/weiyu/miniconda3/envs/r4/include -I/home/weiyu/miniconda3/envs/r4/include -Wl,-rpath-link,/home/weiyu/miniconda3/envs/r4/lib  -O3 -std=c++11 -pthread -fPIC -I"./include" -fopenmp -I"./include" -fpic
-fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/weiyu/miniconda3/envs/r4/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifact
s/r-base-split_1639563404388/work=/usr/local/src/conda/r-base-4.1.2 -fdebug-prefix-map=/home/weiyu/miniconda3/envs/r4=/usr/local/src/conda-prefix  -c mmap.cc -o mmap.o
ar rvs ../libn2.a base.o hnsw.o hnsw_node.o distance.o heuristic.o mmap.o
make[1]: ar: No such file or directory
make[1]: *** [Makefile:10: ../libn2.a] Error 127
make[1]: Leaving directory '/tmp/RtmpnEV5N3/R.INSTALL2639f5266e7b1f/N2R/src/n2'
make: *** [Makevars:16: sublibraries] Error 1
ERROR: compilation failed for package ‘N2R’
`
Thanks!

**Comment by evanbiederstedt** [comment]
Hi @ch8316f5eyu 

https://cran.r-project.org/web/packages/N2R/index.html
https://github.com/kharchenkolab/n2r

I'd recommend installing from CRAN via `install.packages(N2R')`

In terms of the compilation errors you're having i.e. `ar: No such file or directory`, there are many things which could be going on there: https://stackoverflow.com/questions/25036228/ar-crs-no-such-file-or-directory

This looks correct `x86_64-conda-linux-gnu-c++ -std=gnu++11 `, but I stay away from miniconda3 

Hope that helps. Best, Evan
