### ISSUE TITLE
Running Overdispersion Pathway Analysis

### ISSUE THREAD

**Issue by airfan0** [kharchenkolab/pagoda2#131]
Hi Pagoda2 team,

I am trying to run your pipeline for finding relevant/significant pathways from my Seurat normalized object. I am currently on the step in the pipeline where I am trying to find the over-dispersed pathways using "testPathwayOverdispersion" and I get the following error. I was wondering if you had any insight as to why I am getting this error and/or how to fix it?

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/98128631/158202434-e7a7dbed-12bb-444a-8af4-41889a0cb843.png">

Thank you so much!
Amna

**Comment by evanbiederstedt** [comment]
Hi @airfan0 

Thanks for the issue. 

I'm seeing this bug come up in the lab too; I don't know whether these bugs always existed, or whether there was a change in R. 

That said, the error is this:

```
> x = 2
> x['foo']
[1] NA
> x$foo
Error in x$foo : $ operator is invalid for atomic vectors
```

I'll fix and update pagoda2 shortly. 

Thanks, Evan

**Comment by evanbiederstedt** [comment]
Hi @airfan0 

There are a few places where this bug could be taking place. If you could, please email me the data you're using (i.e. the pagoda2 object saved as an rds file) or share via Google Drive. 

I'll make sure the fix works from there.

**Comment by evanbiederstedt** [comment]
Another request: @airfan0 

Could you show the code you ran as well? 

As I say, if you are able to share your data + show how to reproducibly create this bug, I'll be able to help

Thanks, Evan
