### ISSUE TITLE
Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) :    0 (non-NA) cases

### ISSUE THREAD

**Issue by Telogen** [kharchenkolab/pagoda2#132]
Hi developer, I' m using pagoda2 to preprocess my dataset before using Conos to integrate scRNA-seq and scATAC-seq data, here are my codes:
```
data <- list(RNA = pbmc.RNA@assays$RNA@counts,
             ATAC= pbmc.ATAC@assays$ACTIVITY@counts)
colnames(data$ATAC) <- paste0(colnames(data$ATAC),'_ATAC')
ATAC_true <- pbmc.ATAC$true
names(ATAC_true) <- paste0(names(ATAC_true),'_ATAC')
# pre-processing using pagoda2
p2l <- lapply(data,basicP2proc,n.cores = 10,get.largevis = F, get.tsne = F)
```
I got the following output:
```
34901 cells, 20287 genes; normalizing ... 
Using plain model 
Winsorizing ... 
log scale ... 
done.

calculating variance fit ...
 using gam 
1116 overdispersed genes ... 1116
persisting ... 
done.
running PCA using 3000 OD genes .
.
.
.
 done

creating space of type angular done
adding data ... done
building index ... done
querying ... done
creating space of type angular done
adding data ... done
building index ... done
querying ... done
0 cells, 23200 genes; normalizing ... 
Using plain model 
Winsorizing ... 
log scale ... 
done.

calculating variance fit ...
 using lm 
Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  0 (non-NA) cases
```
I guess this may result from the gene activity counts matrix of scATAC-seq is got from Cicero, which is not integer:
```
> data$ATAC[1:6,1:6]
6 x 6 sparse Matrix of class "dgCMatrix"
          BMM_R1_15_ATAC BMM_R1_16_ATAC BMM_R1_19_ATAC BMM_R1_21_ATAC BMM_R1_24_ATAC BMM_R1_25_ATAC
7SK                    .   1.149288e-05   1.301992e-06   .              .               .          
A1BG-AS1               .   .              4.495305e-05   0.0001500633   0.0001020802    5.81025e-05
A2M                    .   .              4.495305e-05   .              .               .          
A2M-AS1                .   .              4.495305e-05   .              .               .          
A2ML1                  .   .              .              .              .               .          
A2ML1-AS1              .   .              .              .              .               .          
```
Could you give me some suggestions on how to solve this error?

Best,
Telogen

**Comment by evanbiederstedt** [comment]
Hi @Telogen 

Thanks for using pagoda2. 

Check the output here:
> 34901 cells, 20287 genes; normalizing ... 
vs. 
> 0 cells, 23200 genes; normalizing ... 

All cells were filtered, it appears. There are no cells in the matrix, and hence all steps fail.

Note that `basicP2proc()` is a function meant to quickly process data. In your case, given you're seeing some sort of QC issues, I wouldn't use this. Please check the walkthrough: https://github.com/kharchenkolab/pagoda2/blob/main/doc/pagoda2.walkthrough.md

Start here and go step-by-step to explore what could be going wrong (if anything) with your data: https://github.com/kharchenkolab/pagoda2/blob/main/doc/pagoda2.walkthrough.md#ii-in-depth-processing-and-analysis

Check the expected data structures for the inputs, as well.
