### ISSUE TITLE
Error in extendedP2proc

### ISSUE THREAD

**Issue by Wangxin555** [kharchenkolab/pagoda2#134]
Hi,

I am using `extendedP2proc` function to analysis sc-sequencing data and I encounter an error

```
> data <- read10xMatrix("../GSE157344/example",
                      transcript.id = "ENSEMBL")

# performs all basic pagoda2 processing
> dat_processed <- basicP2proc(data, n.cores=1, min.cells.per.gene=10, 
                             n.odgenes=2e3, get.largevis=FALSE, 
                             make.geneknn=FALSE)

> ext.res <- extendedP2proc(dat_processed, organism = 'hs')
determining valid pathways
processing 0 valid pathways
scoring pathway od signifcance
Error in uniroot(function(x) { : 
  f() values at end points not of opposite sign
```
Data comes from one of samples in GSE157344 dataset.

The sessionInfo is as below:
```
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)
```

Any idea about how to solve this problem? Thanks!

**Comment by evanbiederstedt** [comment]
Please check the tutorial and run each step one by one

There’s probably a more informative error there for you to debug.

‘ basicP2proc()’ was meant to be a single function that would process
everything at once——it often doesn’t work that way

Thanks Evan
