### ISSUE TITLE
Error in hdea

### ISSUE THREAD

**Issue by yojetsharma** [kharchenkolab/pagoda2#137]
I am receiving the following error after the hdea step. I have loaded 10x outputs and ran the commands and faced no issues except at this step:

> > hdea <- r$getHierarchicalDiffExpressionAspects(type='PCA', clusterName='community', z.threshold=3)
> Using community clustering for PCA space
> 
> Error in if (nrow(x) < 1) return(NULL) : argument is of length zero
>

**Comment by evanbiederstedt** [comment]
@yojetsharma 

I would far more details to diagnose this. 

I suspect there's a problem upstream. As far as I know based on other examples, this function isn't buggy.

In any sense, this isn't needed to run Conos, which is what you're discussing in another thread.

**Comment by yojetsharma** [comment]
> `[114`
> [1] Z       M       highest fe      Gene   
> <0 rows> (or 0-length row.names)
> 
> $`115`
> [1] Z       M       highest fe      Gene   
> <0 rows> (or 0-length row.names)
> 
> $`116`
> [1] Z       M       highest fe      Gene   
> <0 rows> (or 0-length row.names)
> 
> $`117`
> [1] Z       M       highest fe      Gene   
> <0 rows> (or 0-length row.names)
> 
> $`118`
> [1] Z       M       highest fe      Gene   
> <0 rows> (or 0-length row.names)
> Warning messages:
> 1: ggrepel: 35 unlabeled data points (too many overlaps). Consider increasing max.overlaps 
> 2: ggrepel: 35 unlabeled data points (too many overlaps). Consider increasing max.overlaps
> > de <- r$diffgenes$PCA[[1]][['3']]
> > r$plotGeneHeatmap(genes=rownames(de)[1:15], groups=r$clusters$PCA[[1]])
> > de <- r$diffgenes$PCA[[1]][['2']]
> > r$plotGeneHeatmap(genes=rownames(de)[1:15], groups=r$clusters$PCA[[1]])
> Warning message:
> In r$plotGeneHeatmap(genes = rownames(de)[1:15], groups = r$clusters$PCA[[1]]) :
>   The following specified genes were not found in the data: [MT-CO2 RPS14 RPS25 DYRK1A MYL6 RPL38 MAGI3 RPL19 TLE4 MT-ND2 LCORL NA NA NA NA], omitting
> Error in if (nrow(x) < 1) return(NULL) : argument is of length zero](url)
These were the warnings that I had received.

**Comment by yojetsharma** [comment]
> [114
> [1] Z M highest fe Gene
> <0 rows> (or 0-length row.names)
> 
> $115
> [1] Z M highest fe Gene
> <0 rows> (or 0-length row.names)
> 
> $116
> [1] Z M highest fe Gene
> <0 rows> (or 0-length row.names)
> 
> $117
> [1] Z M highest fe Gene
> <0 rows> (or 0-length row.names)
> 
> $118
> [1] Z M highest fe Gene
> <0 rows> (or 0-length row.names)
> Warning messages:
> 1: ggrepel: 35 unlabeled data points (too many overlaps). Consider increasing max.overlaps
> 2: ggrepel: 35 unlabeled data points (too many overlaps). Consider increasing max.overlaps
> 
> de <- r$diffgenes$PCA[[1]][['3']]
> r$plotGeneHeatmap(genes=rownames(de)[1:15], groups=r$clusters$PCA[[1]])
> de <- r$diffgenes$PCA[[1]][['2']]
> r$plotGeneHeatmap(genes=rownames(de)[1:15], groups=r$clusters$PCA[[1]])
> Warning message:
> In r$plotGeneHeatmap(genes = rownames(de)[1:15], groups = r$clusters$PCA[[1]]) :
> The following specified genes were not found in the data: [MT-CO2 RPS14 RPS25 DYRK1A MYL6 RPL38 MAGI3 RPL19 TLE4 MT-ND2 LCORL NA NA NA NA], omitting
> Error in if (nrow(x) < 1) return(NULL) : argument is of length zero](url)

These were the warnings that I had received.
