### ISSUE TITLE
keep.limits triggers error in plotEmbedding

### ISSUE THREAD

**Issue by teng-gao** [kharchenkolab/pagoda2#139]
In `pagoda$plotEmbedding`, keep.limits = T is supposedly able to help maintain axis limits while `plot.na = F`, but it triggers an error:
```
Error in embedding[, 1]: incorrect number of dimensions
```

**Comment by evanbiederstedt** [comment]
It's been almost a year. I realistically won't get to this bug any time soon.

It shouldn't be that complicated to fix. 

Maybe it's something fun for @rrydbirk or others in his lab/group to fix. @teng-gao might have fun tackling this as well.

I'll put a help wanted ticket here.

**Comment by rrydbirk** [comment]
Fixed in [f65d0d6](https://github.com/rrydbirk/pagoda2/commit/f65d0d695523fc4ebb808aef69ebf82eb8b96ae9), I'll create a PR.
