### ISSUE TITLE
Report a small bug

### ISSUE THREAD

**Issue by Junedays** [kharchenkolab/pagoda2#140]
Here to report a bug. 

for this line: 

emat <- filter.genes.by.cluster.expression(emat,cluster.label,min.max.cluster.average = 0.5)

There will be an error if any one of the clusters have only one cell. This is due to the reason that rowMean calculation requires at least two cells so as the input matrix has two dimension. 

We can delete those clusters with only one cell beforehand to solve this problem. 

And I hope this could be fixed in the next version.

**Comment by evanbiederstedt** [comment]
@Junedays 
Thanks for reporting this; it sounds like this is an error in logic we could fix pretty quickly

I'll try to do it ASAP

**Question:**

Besides this:
```
emat <- filter.genes.by.cluster.expression(emat,cluster.label,min.max.cluster.average = 0.5)
```

Could you provide a fully reproducible example? https://github.com/kharchenkolab/pagoda2/blob/main/doc/pagoda2.walkthrough.md

Beginning with:

```
library(pagoda2)
cm <- p2data::sample_BM1
.....
```

That will save me time + help me fix this relatively soon

Thanks, Evan

**Comment by Junedays** [comment]
> @Junedays Thanks for reporting this; it sounds like this is an error in logic we could fix pretty quickly
> 
> I'll try to do it ASAP
> 
> **Question:**
> 
> Besides this:
> 
> ```
> emat <- filter.genes.by.cluster.expression(emat,cluster.label,min.max.cluster.average = 0.5)
> ```
> 
> Could you provide a fully reproducible example? https://github.com/kharchenkolab/pagoda2/blob/main/doc/pagoda2.walkthrough.md
> 
> Beginning with:
> 
> ```
> library(pagoda2)
> cm <- p2data::sample_BM1
> .....
> ```
> 
> That will save me time + help me fix this relatively soon
> 
> Thanks, Evan


Hi. The reason I noticed this problem is that I was using the clustering and embedding information from Seurat, nor using them from the PCA from you pagoda2 packages.  In Seurat when you increase the resolution during the clustering, you can get more clusters and more likely to have some of them having only 1 cell. It is very easy to replicate that using sample data from Seurat.

**Comment by evanbiederstedt** [comment]
>It is very easy to replicate that using sample data from Seurat.

Ok, could you provide this code for me which replicates this please? Example dataset and code from you, and then I'll be able to isolate the bug and fix. 

Less guesswork on my part will speed this whole process up

**Comment by Junedays** [comment]
> > It is very easy to replicate that using sample data from Seurat.
> 
> Ok, could you provide this code for me which replicates this please? Example dataset and code from you, and then I'll be able to isolate the bug and fix.
> 
> Less guesswork on my part will speed this whole process up


Ok, Can I have you email? I can send you

**Comment by evanbiederstedt** [comment]
Hi @Junedays 

Sorry, I replied earlier but it looks like it didn't save. 

RE: email
https://dbmi.hms.harvard.edu/people/evan-biederstedt

However, you don't need to send me your private data;. Doesn't Seurat have some basic data to work with?

If not, Pagoda2 has the following:

```
install.packages('p2data', repos='https://kharchenkolab.github.io/drat/', type='source')
countMatrix <- p2data::sample_BM1
```

https://github.com/kharchenkolab/pagoda2/blob/main/doc/pagoda2.walkthrough.md


Thanks, Evan

**Comment by evanbiederstedt** [comment]
@Junedays 

Were you ever able to find a reproducible example for me to follow? That would be helpful

Best, Evan

**Comment by evanbiederstedt** [comment]
I think this is related to a `velocyto.R` snippet of code: 

```
filter.genes.by.cluster.expression <- function(emat,clusters,min.max.cluster.average=0.1) {
  if(!any(colnames(emat) %in% names(clusters))) stop("provided clusters do not cover any of the emat cells!")
  vc <- intersect(colnames(emat),names(clusters))
  cl.emax <- apply(do.call(cbind,tapply(vc,as.factor(clusters[vc]),function(ii) Matrix::rowMeans(emat[,ii]))),1,max)
  vi <- cl.emax>min.max.cluster.average;
  emat[vi,]
}
```

I'll close until there's a reproducible example I could use to quickly debug and fix.
