### ISSUE TITLE
Mat::init(): requested size is too large; suggest to enable ARMA_64BIT_WORD

### ISSUE THREAD

**Issue by wresch** [kharchenkolab/pagoda2#142]
A user on our cluster gets the following with `aramCor` from pagoda2:

```R
install.packages("pagoda2")
library(pagoda2)
emb <- matrix(rnorm(108640 * 50), nrow=108640, ncol=50)
cell.dist <- as.dist(1-armaCor(t(emb)))
```
```
Error: Mat::init(): requested size is too large; suggest to enable ARMA_64BIT_WORD
```

I attempted to install pagoda2 after adding
```
PKG_CPPFLAGS = -DARMA_64BIT_WORD=1
```
to Makevars but get compile errors (see attached log).

Am i doing something wrong or is this a known limitation?

R 4.2.2, gcc 9.2.0, MKL numerical libraries

[compile.log](https://github.com/kharchenkolab/pagoda2/files/11192652/compile.log)

**Comment by evanbiederstedt** [comment]
Thanks for using the tool! This is not related to pagoda2:

https://community.rstudio.com/t/error-computing-large-data-requested-size-is-too-large-suggest-to-enable-arma-64bit-word/154016

https://github.com/FredHutch/easybuild-life-sciences/issues/124

Check compiling RcppArmadillo to be 64-bit compatible. There are a few other StackOverflow discussions about this as well. 

Best, Evan

**Comment by wresch** [comment]
Sorry if i'm being dense but here is the relevant section from `RcppArmadillo/config/RcppArmadilloConfig.h`

```
// Under C++11 and C++14, Armadillo now defaults to using int64_t for
// integers.  This prevents us from passing integer vectors to R as
// only used int32_t -- so we select the shorter representation here.
// Unless int64_t is explicitly required during compilation.
#if !defined(ARMA_64BIT_WORD)
  #define ARMA_32BIT_WORD 1
#endif
```

**Comment by wresch** [comment]
Thanks for indulging me @evanbiederstedt . Here is a test i just tried:

**Comment by wresch** [comment]
Unfortunately naively trying to compile pagoda with `-DARMA_64BIT_WORD=1` didn't work. Maybe i'll suggest to the user to take the code above if it is the only limiting factor (and it can fit into memory somewhere)

**Comment by evanbiederstedt** [comment]
Thanks @wresch 

If you can find the issue causing the compilation issue, please make a PR. 

Otherwise, I'm not sure how to fix this for users such that it's CRAN compatible

**Comment by wresch** [comment]
I will suggest using just the stripped down `armaCor` version from above to my colleague first. I don't know Rcpp, RcppArmadillo etc that well and I'm not sure I could come up with a PR that I would be comfortable with in a reasonable time frame. I'll let you know if things change.  Thanks again for taking the time to disuss

**Comment by evanbiederstedt** [comment]
Well, I'm happy to add `#define ARMA_64BIT_WORD 1` in the next release. 

I think there are a few other packages whereby I do something like this. I'll try to do this ASAP. 

Thanks for the help. Best, Evan

**Comment by evanbiederstedt** [comment]
Related SO post for future reference: https://stackoverflow.com/questions/40592054/large-matrices-in-rcpparmadillo-via-the-arma-64bit-word-define

**Comment by evanbiederstedt** [comment]
@wresch 

Well, I'm trying to figure out how to do this. 
https://stackoverflow.com/questions/40592054/large-matrices-in-rcpparmadillo-via-the-arma-64bit-word-define

I thought this approach would work:

```
#define ARMA_64BIT_WORD 1
#include <RcppArmadillo.h>
// [[Rcpp::depends(RcppArmadillo)]]
// [[Rcpp::plugins(cpp11)]] 
```

I get compilation errors:
```
/Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppArmadillo/include/armadillo_bits/Col_bones.hpp:36:10: note: candidate constructor not viable: requires 0 arguments, but 4 were provided
  inline Col();
         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [misc2.o] Error 1
ERROR: compilation failed for package ‘pagoda2’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/pagoda2’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/pagoda2’
```

If you find a way I could put this in the package, I'm happy to update on CRAN

Thanks, Evan
