### ISSUE TITLE
pagoda2WebApp_readStaticFile function does not work

### ISSUE THREAD

**Issue by Auryllius** [kharchenkolab/pagoda2#146]
Hello, 
I'm using Pagoda2 ver. 1.0.12 and able to create the web app through the tutorial provided here. 
However, when I want to work on the bin files (which were also created by using pagoda), I cannot upload the files to the R environment. Specifically, I'm trying to use pagoda2WebApp_readStaticFile function and when I try to use this function, I get this error message: pagoda2WebApp_readStaticFile' is not an exported object from 'namespace:pagoda2'

```
p2web <- pagoda2::pagoda2WebApp_readStaticFile(filename=`"**/PATH TO BIN FILE**"`)
pagoda2::show.app(app=p2web, name="app",ip= "127.0.0.1")
```
Since I can't load the bin file to the environment, I can't use the show.app function. How can I load the bin files? Thanks in advance.

**Comment by evanbiederstedt** [comment]
Hi @Auryllius 

Apologies for the late reply; we may have spoken on email. 

It's been a few years since I've looked at this. It's possible there's a slight bug somewhere. 

Many of the internal libraries used to work with static web servers were modified as well. 

Could you simply email me a copy of your bin file? See my Gmail. That's the easiest/quickest solution. I'll find some time to fix this. 

Best, Evan

**Comment by Auryllius** [comment]
Hi @evanbiederstedt 
Thanks for the reply and no worries, I'm uploading a couple of bin files to the drive so I can forward them to you. 
Best, Muhlis

**Comment by evanbiederstedt** [comment]
I think I'll need to update the tutorial. After running `show.app()`, users will want to upload `*.bin` files

Basically, the following code is relevant: https://github.com/kharchenkolab/pagoda2/blob/main/inst/rookServerDocs/js/p2globalParams.js#L14-L34

Add '?dataconfiguration=filelocal' to the end of the `index.html`

You'll see the window pop up "Pagoda2 file selection", and you can upload *.bin files there. 

I should also clarify that users should *really* save the `*.rds` files.

<img width="1023" alt="file_upload_window (1)" src="https://github.com/user-attachments/assets/dcea5a5c-c187-45ea-97c0-6ebe3f2ff095">

**Comment by Auryllius** [comment]
Hi Evan, 

Thank you for the solution and your comments!

Best!
