### ISSUE TITLE
Error in extendedP2proc 

### ISSUE THREAD

**Issue by vixenk** [kharchenkolab/pagoda2#147]
Hi, 
I am trying to run standert pagoda2  pipeline on my Harmony integrated and normalized and scaled data, but I get error during scoring pathway od signifcance step:

```
> pgd <- Pagoda2$new(as(merged_obj_harmonized[['RNA']]$scale.data, "dgCMatrix"), modelType="raw")
> pgd.res <- extendedP2proc(pgd, organism = 'hs')

determining valid pathways
processing 875 valid pathways
scoring pathway od signifcance
Error in x$n : $ operator is invalid for atomic vectors
In addition: Warning message:
In mclapply(..., mc.cores = n.cores, mc.preschedule = mc.preschedule) :
  all scheduled cores encountered errors in user code
```

Could you please suggest what might be wrong?

**Comment by evanbiederstedt** [comment]
Hi @vixenk 

Thanks for using pagoda2. 

> Error in x$n : $ operator is invalid for atomic vectors

This is data type error, e.g. cf here: https://stackoverflow.com/questions/23299684/r-error-in-xed-operator-is-invalid-for-atomic-vectors.

When you initialize the Pagoda2 object here:

> pgd <- Pagoda2$new(as(merged_obj_harmonized[['RNA']]$scale.data, "dgCMatrix"), modelType="raw")

there's probably some issue in terms of the inputs. I cannot easily debug from here. 

If you check the function `extendedP2proc()`, you'll see it's here: 

https://github.com/kharchenkolab/pagoda2/blob/main/R/pipelineHelpers.R#L60-L89

(1) I would therefore recommend running the function/method ` testPathwayOverdispersion()` line by line. That should help you find the bug. It's originally from here: https://github.com/hms-dbmi/scde

(2) I'm guessing you'll be able to find the issue earlier if you follow "Part 2" here: https://github.com/kharchenkolab/pagoda2/blob/main/doc/pagoda2.walkthrough.md#part-2-analysing-data-with-pagoda2

Those other methods may throw errors if the initialized Pagoda2 object isn't exactly as expected. There could possibly be some strange issue with Matrix datatypes. 

Hopefully that helps. 

Best, Evan
