### ISSUE TITLE
Multicore tSNE calculation issue

### ISSUE THREAD

**Issue by barkasn** [kharchenkolab/pagoda2#23]
I encountered the following error when running tSNE on a 50k cell dataset:

 Error: C stack usage  97164344788 is too close to the limit                                                                                
 terminate called after throwing an instance of 'std::bad_alloc'                                                                            
   what():  std::bad_alloc   

This is really a multicore tSNE bug, but it should be trapped correctly in pagoda and reported appropriately to the user.

**Comment by JEFworks** [comment]
Same here. However this is not an issue with the regular RTsne package with openmp multi core support. I would recommend switching back to the regular RTsne package.

Sent from my iPhone

On Oct 25, 2017, at 8:40 PM, Nikolas Barkas <notifications@github.com<mailto:notifications@github.com>> wrote:


I encountered the following error when running tSNE on a 50k cell dataset:

Error: C stack usage 97164344788 is too close to the limit
terminate called after throwing an instance of 'std::bad_alloc'
what(): std::bad_alloc

This is really a multicore tSNE bug, but it should be trapped correctly in pagoda and reported appropriately to the user.

**Comment by barkasn** [comment]
I remember this being resolved, closing
