### ISSUE TITLE
Core functionality is undocumented

### ISSUE THREAD

**Issue by barkasn** [kharchenkolab/pagoda2#25]
Core functionality is undocumented

**Comment by emmanuelaaaaa** [comment]
Hello, 
I agree, more details are needed on what the functions actually do and alternative options for their arguments. At the moment, people can only try the code of the vignette but can't go much further without help pages.

**Comment by barkasn** [comment]
@evanbiederstedt I am not sure about the state of documentation right now, tutorials are much more advanced, I think it can be closed

**Comment by evanbiederstedt** [comment]
I think going through the documentation again is on the list; no need to have an issue open.
