### ISSUE TITLE
What is the underlying method for correcting batch effect in pagoda2?

### ISSUE THREAD

**Issue by ahy1221** [kharchenkolab/pagoda2#27]
Hi
I am interested in correcting multiple batch factors using pagoda2 method. It seems that currently only one batch factor can be used as input.
The batch effect correction method from the code 

      if(!is.null(batch)) {

          cat("batch ... ")
          # dataset-wide gene average
          gene.av <- (Matrix::colSums(counts)+length(levels(batch)))/(sum(depth)+length(levels(batch)))
          # pooled counts, df for all genes
          tc <- colSumByFac(counts,as.integer(batch))[-1,,drop=F]
          tc <- t(log(tc+1)- log(as.numeric(tapply(depth,batch,sum))+1))
          bc <- exp(tc-log(gene.av))
          # adjust every non-0 entry
          count.gene <- rep(1:counts@Dim[2],diff(counts@p))
          counts@x <<- counts@x/bc[cbind(count.gene,as.integer(batch)[counts@i+1])]
      }

looks like that we are calculating a scale factor  as CPM_{g,batch} / CPM_{g}, then we use the raw counts of each gene in each cell to divide this scale factor as rescaled counts. Is that right ?

I wonder that what is intuitive explanation for this scale factor ? What if I want to rescaled the counts again by another factor such as cell cycling phase ?

Thanks

**Comment by ahy1221** [comment]
Another thing is that why should we need add length(levels(batch)) for calculating gene.av ?
`gene.av <- (Matrix::colSums(counts)+length(levels(batch)))/(sum(depth)+length(levels(batch)))` 

Thanks

**Comment by evanbiederstedt** [comment]
Batch correction methods in pagoda2 are somewhat crude. I would recommend looking at https://github.com/kharchenkolab/conos
