### ISSUE TITLE
test.stability parameter in getKnnClusters breaks web app visualization

### ISSUE THREAD

**Issue by VPetukhov** [kharchenkolab/pagoda2#42]
I used the following code on data with 4 clusters (1, 2, 3 and 4):
```r
p2 <- basicP2proc(countMatrix, n.cores = 20)
p2$getKnnClusters(method = igraph::infomap.community, type = 'PCA' ,name = 'infomap', test.stability=T, plot=T)
```

After that, names of some clusters become string like "2 + 3", meaning, if I understood correctly, that these clusters were merged. Afterwards, I run webapp with the following code:

```r
ext.res <- extendedP2proc(p2, n.cores = 20, organism = 'mm')

p2 <- ext.res$p2
go.env <- ext.res$go.env
rm(ext.res)

metadata.listfactors <- list(
    infomap = p2$clusters$PCA$infomap,
    multilevel = p2$clusters$PCA$multilevel,
    walktrap = p2$clusters$PCA$walktrap
);
metadata.forweb <- factorListToMetadata(metadata.listfactors)

p2.webobject <- webP2proc(p2, additionalMetadata = metadata.forweb, title = 'P2App', go.env = go.env)
p2.webobject$mainDendrogram$cluster.sizes
p2.webobject$serializeToStaticFast('serialisedApp.bin');

show.app(p2.webobject, name="P2App", browse = T)
```

JavaScript part iterates over integer indexes and fails to understand string cluster name.

**Comment by barkasn** [comment]
Thank you Viktor, if you can save the session and send it to me I'll look into this

**Comment by pkharchenko** [comment]
May be we should turn off test.stability option for now. I’ve implemented a different set of routines for this type of analysis (mendel:/home/pkharchenko/p2/clstability.r), but didn’t have a chance to incorporate them yet. Not entirely happy with the way they work either.
-peter.

**Comment by barkasn** [comment]
ok, sounds good. I wrote to Viktor in a separate email about this that this is not urgent, however I would like to get the web interface not to break if the cluster names are not numeric, so I do want to get to look into this at some poitnt

**Comment by barkasn** [comment]
@evanbiederstedt I am not sure about the status of this

**Comment by evanbiederstedt** [comment]
@VPetukhov This is still a valid issue, I am guessing?

**Comment by pkharchenko** [comment]
We should probably take it out of p2. Cluster stability would be a feature that we'd want to have in both conos and p2. It's rarely used though, CPU intensive, and in the current form is not particularly user-friendly. The main issue is that to do this properly one needs a fast hierarchical community detection method, which we don't currently have. It might be that alternative approaches (e.g. classifier based confusion matrix, or meta-cell like calculations) will be more effective.

**Comment by VPetukhov** [comment]
> @VPetukhov This is still a valid issue, I am guessing?

Perhaps. I didn't test it since then though.

**Comment by evanbiederstedt** [comment]
Hi @VPetukhov 

I'm interested in seeing whether the JS integer/string error still exists, i.e. 

> JavaScript part iterates over integer indexes and fails to understand string cluster name.

I've been struggling to reproduce the error you detail above---I thought this would be straightforward, but I keep running into other errors. 

Could you give me a `countMatrix` which reproduces the behavior you saw previously? I would then like to use this code:

```
p2 <- basicP2proc(countMatrix, n.cores = 20)
p2$getKnnClusters(method = igraph::infomap.community, type = 'PCA' ,name = 'infomap', test.stability=T, plot=T)

ext.res <- extendedP2proc(p2, n.cores = 20, organism = 'mm')

p2 <- ext.res$p2
go.env <- ext.res$go.env
rm(ext.res)

metadata.listfactors <- list(
    infomap = p2$clusters$PCA$infomap,
    multilevel = p2$clusters$PCA$multilevel,
    walktrap = p2$clusters$PCA$walktrap
);
metadata.forweb <- factorListToMetadata(metadata.listfactors)

p2.webobject <- webP2proc(p2, additionalMetadata = metadata.forweb, title = 'P2App', go.env = go.env)
p2.webobject$mainDendrogram$cluster.sizes
p2.webobject$serializeToStaticFast('serialisedApp.bin');

show.app(p2.webobject, name="P2App", browse = T)
```

Naturally, if you could reproduce the error in other ways, that would be appreciated as well. Thanks!
