### ISSUE TITLE
how to control cluster numbers?

### ISSUE THREAD

**Issue by lixin4306ren** [kharchenkolab/pagoda2#50]
I tried different cluster methods (infomap, multilevel, walktrap) on ~2000 cells, and always got over 15 clusters. By eyes, there should be many clusters. How can I lower the cluster numbers? Any parameters I can adjust? Thanks.

**Comment by VPetukhov** [comment]
It's not a real answer on the question, but you can vary number of principal components used for clustering. Based on my experience, lower number of PCs lead to rougher clustering.

**Comment by pkharchenko** [comment]
Hi Xin,
 We use community detection methods implemented by the igraph package. Unfortunately most of them do not provide parameters that could be used to adjust granularity. Switching methods typically results in different granularity (e.g. infomap.community typically gives finer clusters than multilevel.community). Decreasing k also tends to generate smaller clusters. I would not recommend reducing PCs (below 10 anyway), as this is more likely to generate artifacts. 
 We’re open for recommendations for community detection methods that can be better controlled. 
Best,
-peter.

**Comment by evanbiederstedt** [comment]
Issue addressed, I think
