### ISSUE TITLE
Possibly wrong axis labels for the plot generated by `$adjustVariance`

### ISSUE THREAD

**Issue by mt1022** [kharchenkolab/pagoda2#51]
I am running this [walkthrough](http://pklab.med.harvard.edu/peterk/p2/walkthrough.nb.html) and got the adjusted variance as shown in that webpage after executing this line:
```
r$adjustVariance(plot=T,gam.k=10)
```
However, based on your R code [here](https://github.com/hms-dbmi/pagoda2/blob/e23c831e857b342ba34627d5cc9dd92ae7e299d8/R/Pagoda2.r#L196), the axis label should be `xlab='log[ magnitude ]',ylab='log[ variance ]'` rather than `xlab='log10[ magnitude ]',ylab='log10[ variance ]'`. The plot code ([here](https://github.com/hms-dbmi/pagoda2/blob/e23c831e857b342ba34627d5cc9dd92ae7e299d8/R/Pagoda2.r#L266) and [here](https://github.com/hms-dbmi/pagoda2/blob/e23c831e857b342ba34627d5cc9dd92ae7e299d8/R/Pagoda2.r#L272)) seems to be wrong.

I am not sure whether my understanding is correct. Can you verify this?

**Comment by evanbiederstedt** [comment]
Fixed here: https://github.com/kharchenkolab/pagoda2/issues/51
