### ISSUE TITLE
subset data based on clusters

### ISSUE THREAD

**Issue by DRLaks** [kharchenkolab/pagoda2#58]
Is there a method or code to subset the data, the pagoda2 object, based on clusters?

**Comment by evanbiederstedt** [comment]
Yes, if I understand your question. Based on the [vignettes](https://github.com/kharchenkolab/pagoda2/blob/master/vignettes/pagoda2.walkthrough.oct2018.Rmd), let's say you were to generate clusters as follows:

```
r$makeKnnGraph(k=40,type='PCA',center=T,distance='cosine')
r$getKnnClusters(method=infomap.community,type='PCA')
```

Then you should be able to access a list of clusters as follows with `r$clusters$PCA$community`, and subset them as needed:

```
head(r$clusters$PCA$community)
MantonBM1_HiSeq_1-TCTATTGGTCTCTCGT-1 MantonBM1_HiSeq_1-GAATAAGTCACGCATA-1 
                                   5                                    1 
MantonBM1_HiSeq_1-ACACCGGTCTAACTTC-1 MantonBM1_HiSeq_1-TCATTTGGTACGCTGC-1 
                                   1                                    6 
MantonBM1_HiSeq_1-TATTACCCAAAGGAAG-1 MantonBM1_HiSeq_1-CGCCAAGCATCTGGTA-1 
                                   6                                    1 
Levels: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22
```

Note that the pagoda2 object here is `r`.
