### ISSUE TITLE
Add walktrap clustering to pagoda with option to specify number of clusters

### ISSUE THREAD

**Issue by VPetukhov** [kharchenkolab/pagoda2#62]
Walktrap clustering allows to easily select number of clusters:

```r
walktrap_clusters <- igraph::cluster_walktrap(p2$graphs$PCA) %>% as.hclust() %>% cutree(k=8)
```

Perhaps, it would be pretty useful feature, which already been requested (see https://github.com/hms-dbmi/pagoda2/issues/50). I think, we can add parameter `n.clusters=NULL` to `getKnnClusters` function. This option is ignored with a warning if `!isTRUE(all.equal(method, igraph::walktrap.community)) && !is.null(n.clusters)`.

@pkharchenko what do you think about it?

**Comment by pkharchenko** [comment]
Sounds useful, though given that walktrap is quite slow, this wouldn’t be the right way of playing around with the number of clusters. 
If we start re-using walktrap clustering objects ( current cached in $misc[['community']][[type]][[name]]), then we’d also need to provide control of that cache (i.e. recalculating vs. re-using cached result)
It seems simpler to just show people how to make a new factor using walktrap results, or make a helper method for it. As you know, Conos will have an interactive interface to do explore different cut levels (for multi-dataset analysis).

**Comment by VPetukhov** [comment]
So, the new Conos functionality isn't actually used. But instead we have `findSubcommunities` there, which was very useful at least for me. And the walktrap doesn't work well anyway. I think, this Pagoda issue could be just closed.
