### ISSUE TITLE
Installation failed on a test stage.

### ISSUE THREAD

**Issue by pavelmor** [kharchenkolab/pagoda2#63]
Hi,

I have a problem of installing pagoda2 on a RedHat machine and all seems to go fine, just a few warnings, but it failed of the test stage: 
...
```
** testing if installed package can be loaded
Error: package or namespace load failed for ‘pagoda2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/pmorozov/R/x86_64-redhat-linux-gnu-library/3.5/pagoda2/libs/pagoda2.so':
  libgsl.so.23: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/pmorozov/R/x86_64-redhat-linux-gnu-library/3.5/pagoda2’
Installation failed: Command failed (1)
```
...

Can you help,
Pavel.

**Comment by barkasn** [comment]
Hi Pavel,

Pagoda2 requires the GNU Scientific Library to be installed on the system. You either don't have it installed or the linker can't find the corresponding object: "libgsl.so.23"

Please verify that you have the library install and if not install it via yum. If the library is installed but the error persists then the file cannot be found at linking time. The easiest way to solve this is by adding it to LIBRARY_PATH and LD_LIBRARY_PATH variables in your environment.

I hope this helps, please let me know if resolves the issue or you continue to have problems.

Best wishes,

Nikolas

**Comment by barkasn** [comment]
Hi Pavel,

We recently released a docker version that you can install. Could you please try to run this (available from the main page) and let us know if it works for you. Other than the docker installation it doesn't require any configuration or compiling.

BW,

Nikolas

**Comment by evanbiederstedt** [comment]
Haven't heard back on this issue. We're working on installation issues elsewhere, which is a pressing goal. I'll close this.
