### ISSUE TITLE
Memory allocation error during t-SNE embedding for large datasets

### ISSUE THREAD

**Issue by VPetukhov** [kharchenkolab/pagoda2#67]
When run pagoda on datasets of more than ~50000 cells, R falls with segfault in `getEmbedding` function:
```R
p2_merged$getEmbedding(type='PCA', embeddingType='tSNE', distance='pearson')
```
```
 *** caught segfault ***
address 0x7f9638dbd188, cause 'memory not mapped'
```

This behaviour is due to attempt to create pairwise distance matrix, which exceeds limit of array size on 32-bit systems (which is about 5e9 elements). On 64-bit systems, memory limit is about 1e19, but R lives in 32-bit world. So, a possible solution would be to estimate correlation matrix and call `Rtsne` directly in C++. It can be done by forking [`Rtsne_cpp`](https://github.com/jkrijthe/Rtsne/blob/master/src/Rtsne.cpp) function.

**Quick solution:** t-SNE on L2 distances still works fine (as it's implemented completely in C++):
```R
p2_merged$getEmbedding(type='PCA', embeddingType='tSNE', distance='L2')
```

**Comment by barkasn** [comment]
Yes this is a known issue and is why basicP2proc uses L2 as the default distance. Would be great if you can improve as the correlation distance is also quite slow to calculate.

**Comment by pkharchenko** [comment]
hmm … L2 is often a poor choice for many datasets, particularly when there’s some depth bias.

**Comment by pkharchenko** [comment]
I don't think this can be easily solved. Rtsne package has a choice of either calculating euclidean distance internally, or providing a full distance matrix. The internal calculations are much more efficient. When L2 metric is used, we essentially delegate to tSNE. When an angular metric is used, we have to calculate cell x cell distance matrix for the tSNE method ... which will be large. The only way around it is to hack the tSNE implementation to support angular distance internally (that way not the full matrix will be calculated, but whatever is needed to build ANN tree).

**Comment by VPetukhov** [comment]
Since we added UMAP (https://github.com/kharchenkolab/pagoda2/commit/e3584c3ec66b41326b88934f00dd3ed539c3eb57), I don't think it's a big problem anymore. There is even a check for matrix side to prevent segfault. So I'm closing the issue.
