### ISSUE TITLE
Remove panel.first = grid() for tSNE

### ISSUE THREAD

**Issue by JEFworks** [kharchenkolab/pagoda2#7]
For the `plotEmbedding` function, if the selected embedding is `tSNE`, then `panel.first = grid()` should not be included in the final `plot(emb, col = adjustcolor(cols, alpha = alpha)...` line.

**Comment by pkharchenko** [comment]
I actually like the grid, but we should have an option to turn it off.

**Comment by JEFworks** [comment]
Grid implies distances can be interpreted. Misleading for tSNE.

Sent from my iPhone

On Aug 23, 2017, at 11:59 AM, pkharchenko <notifications@github.com<mailto:notifications@github.com>> wrote:


I actually like the grid, but we should have an option to turn it off.

**Comment by pkharchenko** [comment]
That’s true. I guess we can turn it off by default.
