### ISSUE TITLE
makeKnnGraph crashes with: "address 0x2b0055be820c, cause 'illegal operand' "

### ISSUE THREAD

**Issue by rlittman16** [kharchenkolab/pagoda2#79]
I am trying to run velocyto with pagoda2, and makeKnnGraph is crashing. Thanks in advanced for your help.

Here is the output of the pipeline so far including the crash:

12823 cells, 24981 genes; normalizing ... using plain model winsorizing ... log scale ... done.
calculating variance fit ... using gam 226 overdispersed genes ... 226 persisting ... done.
running PCA using 3000 OD genes .... done
creating space of type angular done

 *** caught illegal operation ***
address 0x2b0055be820c, cause 'illegal operand'

Traceback:
 1: n2Knn(x, k, nThreads = n.cores, verbose = verbose, indexType = "angular")
 2: r$makeKnnGraph(k = 30, type = "PCA", center = T, distance = "cosine")

**Comment by evanbiederstedt** [comment]
I believe this was due to the compilation of the N2 library portion of the code; recent changes are meant to fix this.
