### ISSUE TITLE
Error in setCountMatrix(x, min.cells.per.gene = min.cells.per.gene, trim = trim,  :    duplicate gene names are not allowed - please reduce

### ISSUE THREAD

**Issue by wupeng2** [kharchenkolab/pagoda2#80]
when I use pogoda on Rstudio,failed on Create pagoda2 object
r2 <- Pagoda2$new(splice,modelType='plain',trim=10,log.scale=T)
Error in setCountMatrix(x, min.cells.per.gene = min.cells.per.gene, trim = trim,  : 
  duplicate gene names are not allowed - please reduce

**Comment by RBBurl1227** [comment]
Hello @wupeng2,
I just received the same error, but was able to get around the problem with some help from a pagoda2 tutorial: http://pklab.med.harvard.edu/peterk/p2/walkthrough.nb.html

By searching the page for the keyword "new" I found the following:

"Now we have a clean/lean count matrix and are ready to start analysis. First we’ll create pagoda2 object that will maintain all of the results. It will also provide handles for running all operations on the data. Use of log scale is recommended, as it makes some statistics smoother.

r <- Pagoda2$new(counts,log.scale=TRUE)
Error in setCountMatrix(x, min.cells.per.gene = min.cells.per.gene, trim = trim,  : 
  duplicate gene names are not allowed - please reduce
Yes, we need to make gene names unique:

rownames(counts) <- make.unique(rownames(counts))
r <- Pagoda2$new(counts,log.scale=TRUE, n.cores=20)
8786 cells, 13004 genes; normalizing ... using plain model winsorizing ... log scale ... done."


So before I made the pagoda object, I first used the below code to make gene names unique in my dataset: 
rownames(counts) <- make.unique(rownames(counts))

This worked for me. Hope this helps!
