### ISSUE TITLE
subtract aspect

### ISSUE THREAD

**Issue by PavelnZ** [kharchenkolab/pagoda2#81]
Hello, 
I am trying to figure out how to reduce the sources of variation in the dataset using Pagoda2. For example, I want to remove the differences between cells in different stages of cell cycle. In the previous version of Pagoda there was a function pagoda.subtract.aspect(). How can I implement this or any similar approach in Pagoda2? 
Hope you can help me,
Thank you!
Pavel

**Comment by evanbiederstedt** [comment]
I suppose we could write a method to do this. My perspective is, `pagoda.subtract.aspect()` was written in a different time, and the method isn't usually best suited for the question at hand---the method would be somewhat of a crutch, when the analysis might require something more statistically sophisticated. Worst case scenario is, the user will be distorting their data.

The simplest idea would be to perform PCA, and regress out the factor in question.

Another crude way to do this would be to build a linear model for each PC, and return the raw residuals.

For reference, the function `pagoda.subtract.aspect()` is [here](https://github.com/hms-dbmi/scde/blob/master/R/functions.R#L1814-L1862)

And the documentation [here](https://www.rdocumentation.org/packages/scde/versions/2.0.1/topics/pagoda.subtract.aspect)

Description:
> Similar to subtracting n-th principal component, the current procedure determines (weighted) projection of the expression matrix onto a specified aspect (some pattern across cells, for instance sequencing depth, or PC corresponding to an undesired process such as ribosomal pathway variation) and subtracts it from the data so that it is controlled for in the subsequent weighted PCA analysis.

Code:
```
pagoda.subtract.aspect <- function(varinfo, aspect, center = TRUE) {
    if(length(aspect) != ncol(varinfo$mat)) { stop("aspect should be a numeric vector of the same length as the number of cells (i.e. ncol(varinfo$mat))") }
    v <- aspect
    v <- v-mean(v)
    v <- v/sqrt(sum(v^2))
    nr <- ((varinfo$mat * varinfo$matw) %*% v)/(varinfo$matw %*% v^2)
    mat.c <- varinfo$mat - t(v %*% t(nr))
    if(center) {
        mat.c <- weightedMatCenter(mat.c, varinfo$matw) # this commonly re-introduces some background dependency because of the matw
    }
    varinfo$mat <- mat.c
    varinfo
}
```
