### ISSUE TITLE
Normalized Counts Units

### ISSUE THREAD

**Issue by drneavin** [kharchenkolab/pagoda2#82]
I am wondering what the units are on the final units on the normalized counts after running Pagoda2$new? For example with the following command: Pagoda2$new(counts.filtered,log.scale=TRUE, n.cores=4, batch =Batch, min.cells.per.gene=1)
would the units be log(counts per thousand) that are batch normalized?

Thanks for your assistance!

**Comment by evanbiederstedt** [comment]
The units are counts per X (whatever value is specified) by depthScale (1e3 by default, `depthScale=1e3` here https://github.com/kharchenkolab/pagoda2/blob/master/R/Pagoda2.r#L77) 

If `log.scale=TRUE` then it is `log(units + 1)` whereby units equals the definition above, "counts per X (whatever value is specified) by depthScale ".
