### ISSUE TITLE
extendedP2proc hanging on "determining valid pathways"

### ISSUE THREAD

**Issue by rrydbirk** [kharchenkolab/pagoda2#83]
I'm running a 10x v3 dataset (~6.5k cells) on 10 cores, 30 GB mem. It has been hanging for 2-3 hours now after running:

p2 <- extendedP2proc(p2, n.cores=10, organism="hs")

Only message is: "determining valid pathways". Should I expect it to run this long?

sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /cm/shared/apps/intel/parallel_studio_xe/2018_update2/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] pagoda2_0.0.0.9002 RLinuxModules_0.2

loaded via a namespace (and not attached):
 [1] igraph_1.2.4         Rcpp_1.0.1           AnnotationDbi_1.44.0
 [4] magrittr_1.5         BiocGenerics_0.28.0  MASS_7.3-51.1
 [7] IRanges_2.16.0       dendsort_0.3.3       bit_1.1-14
[10] lattice_0.20-38      rjson_0.2.20         brew_1.0-6
[13] blob_1.1.1           Rook_1.1-1           tools_3.5.0
[16] parallel_3.5.0       grid_3.5.0           Biobase_2.42.0
[19] irlba_2.3.3          DBI_1.0.0            bit64_0.9-7
[22] digest_0.6.18        Matrix_1.2-15        base64enc_0.1-3
[25] S4Vectors_0.20.1     triebeard_0.3.0      memoise_1.1.0
[28] RSQLite_2.1.1        compiler_3.5.0       GO.db_3.7.0
[31] urltools_1.7.2       pcaMethods_1.74.0    stats4_3.5.0
[34] pkgconfig_2.0.2

**Comment by VPetukhov** [comment]
In this function pagoda connects to GO and it takes surprisingly long. But 2 hours sounds like way too much...

**Comment by rrydbirk** [comment]
Hi Victor, thanks for getting back to me. Today, I have tested with the dataset included in P2 tutorial (sample_BM1.rds) on similar sessions to the one posted above. I tested with 3 different setups on Computerome (which I assume you know, connectivity shouldn't be a problem on my side) to eliminate processing power as a limit. None of the setups finished before my time limit of 2 hours, I get to the same point as above.

Any advice on what to do from here? At the moment, I can't create a web object...

Also, as you can see, for basicP2proc it's not advisable to use too many cores.

> library("pagoda2")
> cm <- readRDS("sample_BM1.rds")

10 cores/30 GB mem:
> system.time(p2 <- basicP2proc(cm, n.cores=10))
   user  system elapsed
 90.091   4.183  43.827

50 cores/50 GB mem:
> system.time(p2 <- basicP2proc(cm, n.cores=50))
   user  system elapsed
 73.491  60.644  47.136

200 cores/100 GB mem:
> system.time(p2 <- basicP2proc(cm, n.cores=200))
   user  system elapsed
114.542 154.400  61.064

**Comment by rrydbirk** [comment]
Lastly, while running debug(p2$testPathwayOverdispersion), the bottom line is where it stalls.

determining valid pathways
debug: gsl <- ls(envir = setenv)
Browse[2]> n
debug: gsl.ng <- unlist(mclapply(sn(gsl), function(go) sum(unique(get(go,
    envir = setenv)) %in% proper.gene.names), mc.cores = n.cores,
    mc.preschedule = T))

**Comment by rrydbirk** [comment]
Problem solved, was caused by local error in parallel package.

**Comment by VPetukhov** [comment]
Hi Rasmus,
Thanks for sharing your solution!

**Comment by pkharchenko** [comment]
Hi Rasmus,
 Just wanted to confirm. The push request is only meant to provide the process bar … correct? Or does it fix an actual bug somewhere? 
Thanks,
-peter.

**Comment by rrydbirk** [comment]
Hi Peter
I'm still struggling with stalling/inconsistent results. The push was meant to try and resolve this, however, my "fix" hasn't changed anything.
Please be advised, I tried to determine valid pathways using 1/2/3/4 cores (object "nc") and repeating it 20 times/#core, these are my results (collected in object "s"):

> table(as.numeric(s[which(nc==1)]))

3193 
  20 
> table(as.numeric(s[which(nc==2)]))

3193 
  20 
> table(as.numeric(s[which(nc==3)]))

3193 3250 
  18    2 
> table(as.numeric(s[which(nc==4)]))

3193 3198 
  17    3 

As you can see, I keep experiencing issues with this function when using multiple cores. Before, I used 20 cores which may be why I experienced stalling.

I don't know if this function should be run without multithreading, or if it's only me who's having these problems?

**Comment by pkharchenko** [comment]
Hi Rasmus,

  Do you have an example somewhere I can run. Which function call do you think is problematic?

Best,
-peter.
