### ISSUE TITLE
Embedding issue in GetDensityClusters

### ISSUE THREAD

**Issue by vkorobeynyk** [kharchenkolab/pagoda2#85]
Dear pagoda2 community,

I have been using this package and I like it a lot.
I am still new in data Science so I am sorry if the questions are too obvious. 
I have encountered several questions:

1- When I create the new pogoda2 env, if I am not mistaken, I get my data transformed to log scale and then Normalized.  What is the normalization used and is it possible to use another one?

2- I have an issue with the function getDensityClusters where I submit the counts but i get the following error: 

my code : `r$getDensityClusters(type = r$counts, embeddingType = r$embeddings)`

`Error in embeddings[[type]] : invalid subscript type 'S4'`
 
Previously I also run : `r$getEmbedding(type='PCA',embeddingType='tSNE',perplexity=50,verbose=T)`

What is a subscript type "S4"?

I dont understand what does this error means. 
Thanks in advance

**Comment by evanbiederstedt** [comment]
Hi @vkorobeynyk 

For normalization, you might want to check this paper: https://www.nature.com/articles/nmeth.4292

For S4 objects and subsetting, this resource might be a good place to begin: http://adv-r.had.co.nz/Subsetting.html

Thanks
