### ISSUE TITLE
where is the entire document?

### ISSUE THREAD

**Issue by wJDKnight** [kharchenkolab/pagoda2#86]
the description in man/Pagoda2-class.rd is not sufficient (getKnnClusters and getEmbedding are not mentioned)? where can I get a complete description of  Pagoda2?

**Comment by evanbiederstedt** [comment]
These functions are mentioned in the vignettes. https://github.com/kharchenkolab/pagoda2/tree/master/vignettes

Naturally, improving the documentation is something we're constantly working on.
